EsibayeniSolution/Models/LivestockImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Web;

namespace EsibayeniSolution.Models
{
    public class LivestockImage
    {
        [Key]
        public int ImageId { get; set; }
        public int LivestockID { get; set; }
        public byte[] Image { get; set; }
        public System.DateTime UploadtDate { get; set; }

        public byte[] setImage(HttpPostedFileBase image1)
        {
            return new byte[image1.ContentLength];
        }  

        public string FileName(HttpPostedFileBase image1)
        {
            image1.InputStream.Read(Image, 0, image1.ContentLength);
            var filename = Path.GetFileName(image1.FileName);
            return filename;
        }
    }
}

EsibayeniSolution/Controllers/LivestockImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsibayeniSolution.Models;
using System.IO;

namespace EsibayeniSolution.Controllers
{
    public class LivestockImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //Renders view with the selected livestock's images
         public ActionResult ViewLivestockImage(int id)
        {
            //joins livestock with the respective images that have that livestock's ID
            var listWthEmpty = from l in db.LivesStocks
                               where l.LivestockID == id
                               join li in db.LivestockImages
                               on l.LivestockID equals li.LivestockID
                               into ThisList
                               from li in ThisList.DefaultIfEmpty()
                               select new LivestockImagesVM
                               {
                                   ImageId = li.ImageId,
                                   LivestockCode = l.Code,
                                   UploadDate = li.UploadtDate
                               };
            return View(listWthEmpty);
        }

        //Downloads and displays the image with the selected ID
        public ActionResult Download(int id)
        {
            var file = db.LivestockImages.Find(id);
            byte[] contents = file.Image;
            return File(contents, "image/jpg");
        }

        // GET: LivestockImages/Create
        [Authorize(Roles = "Livestock Controller")]
        public ActionResult Create(LivesStock livestock)
        {
            LivestockImage livestockImage = new LivestockImage();
            //links the image to be uploaded, with the selected livestock
            livestockImage.LivestockID = livestock.LivestockID;
            //takes the livestockImage with the livestockID to the image upload screen
            return View(livestockImage);
        }

        // POST: LivestockImages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImageId,LivestockID,Image,UploadtDate")] LivestockImage livestockImage, HttpPostedFileBase image1)
        {
            if (ModelState.IsValid)
            {
                //if an image is selected
                if (image1 != null && image1.ContentLength > 0)
                {
                    livestockImage.UploadtDate = DateTime.Now;
                    livestockImage.Image = livestockImage.setImage(image1);
                    var path = Path.Combine(Server.MapPath("~/App_Data"), livestockImage.FileName(image1));
                    image1.SaveAs(path);
                }
                db.LivestockImages.Add(livestockImage);
                db.SaveChanges();
                return RedirectToAction("Index", "LivesStocks");
            }

            return View(livestockImage);
        }
        // GET: LivestockImages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LivestockImage livestockImage = db.LivestockImages.Find(id);
            if (livestockImage == null)
            {
                return HttpNotFound();
            }
            return View(livestockImage);
        }

        // POST: LivestockImages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LivestockImage livestockImage = db.LivestockImages.Find(id);
            db.LivestockImages.Remove(livestockImage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

EsibayeniSolution/Views/LivestockImages/Create.cshtml
@model EsibayeniSolution.Models.LivestockImage

@{
    ViewBag.Title = "Upload Livestock Image";
}

<h2>Upload Livestock Image</h2>


@using (Html.BeginForm("Create", "LivestockImages", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Upload Livestock Image</h4>
        <hr />
        @Html.Raw(TempData["Message"])
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LivestockID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.LivestockID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LivestockID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="image1" name="image1" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload Image" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EsibayeniSolution/Views/LivestockImages/Delete.cshtml
@model EsibayeniSolution.Models.LivestockImage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LivestockImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LivestockID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LivestockID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadtDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadtDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EsibayeniSolution/Views/LivestockImages/ViewLivestockImage.cshtml
@model IEnumerable<EsibayeniSolution.Models.LivestockImagesVM>

@{
    ViewBag.Title = "Livestock Image";
}

<h2>Livestock Image</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LivestockCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UploadDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <a href="@Url.Action("Download","LivestockImages",new { id=item.ImageId})">@Html.DisplayFor(modelItem => item.ImageId)</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LivestockCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UploadDate)
        </td>
@if (Request.IsAuthenticated && !User.IsInRole("") && !User.IsInRole("Customer"))
{
    <td>
        @Html.ActionLink("Delete", "Delete", new { id = item.ImageId })
    </td>
}
    
    </tr>
}

</table>